--- name:exoter_bb2
# gaussian kernel for dense stereo pre-processing.
gaussian_kernel: 0
# if set to true, the input images are assumed to already be rectified.
image_rectified: false
# if set to true, the input images are assumed to be rotated by 180 degrees.
image_rotated: false
# down- or upscale input images by this factor.
image_scaling_factor: 1.0
# configuration values for libElas
libElas_conf:
  disp_min: 0
  disp_max: 350
  support_threshold: 0.8500000238418579
  support_texture: 10
  candidate_stepsize: 5
  incon_window_size: 5
  incon_threshold: 5
  incon_min_support: 5
  add_corners: true
  grid_size: 20
  beta: 0.019999999552965164
  gamma: 3.0
  sigma: 1.0
  sradius: 2.0
  match_texture: 1
  lr_threshold: 2
  speckle_sim_threshold: 1.0
  speckle_size: 200
  ipol_gap_width: 3
  filter_median: false
  filter_adaptive_mean: true
  postprocess_only_left: true
  subsampling: false
# configuration for sparse features.
sparse_config:
  debugImage: true
  targetNumFeatures: 100
  maxStereoYDeviation: 5
  knn: 1
  distanceFactor: 2
  isometryFilterMaxSteps: 1000
  isometryFilterThreshold: 0.1
  adaptiveDetectorParam: false
  detectorConfig:
    SURFparam: 170
    goodParam: 0.10000000149011612
    mserParam: 3.0
    starParam: 9.0
    fastParam: 12.0
  descriptorType: :DESCRIPTOR_PSURF
  detectorType: :DETECTOR_MSER
  filterType: :FILTER_STEREO
# calibration parameters for stereo camera intrinsics and extrinsics
stereoCameraCalibration:
  camLeft:
    fx: 836.06946050655949
    fy: 836.14916268708816
    cx: 516.37155418305281
    cy: 377.29889017486101
    d0: -0.3389695490988
    d1:  0.1217553065872
    d2:  0.0002936920143
    d3:  0.0000878463732
    width: 1024
    height: 768
  camRight:
    fx: 832.27804742153376
    fy: 832.56239966940871
    cx: 507.37637964982628
    cy: 380.63748343529795
    d0: -0.33914092102560
    d1:  0.12092692896553
    d2:  0.00062442626516
    d3: -0.00038293414690
    width: 1024
    height: 768
#Distance between left and right camera
  extrinsic:
    tx: -120.01886209277160
    ty: 0.25901217247349007
    tz: 0.34917543917589172
    rx: 0.003734249504278
    ry: 0.006861413405440
    rz: -0.000787881379522
output_format_sync: :MODE_GRAYSCALE

--- name:hdpr_bb2
# gaussian kernel for dense stereo pre-processing.
gaussian_kernel: 0
# if set to true, the input images are assumed to already be rectified.
image_rectified: false
# if set to true, the input images are assumed to be rotated by 180 degrees.
image_rotated: false
# down- or upscale input images by this factor.
image_scaling_factor: 1.0
# configuration values for libElas
libElas_conf:
  disp_min: 5
  disp_max: 350
  support_threshold: 0.8500000238418579
  support_texture: 10
  candidate_stepsize: 5
  incon_window_size: 5
  incon_threshold: 5
  incon_min_support: 5
  add_corners: false
  grid_size: 20
  beta: 0.019999999552965164
  gamma: 3.0
  sigma: 1.0
  sradius: 2.0
  match_texture: 1
  lr_threshold: 2
  speckle_sim_threshold: 1.0
  speckle_size: 200
  ipol_gap_width: 3
  filter_median: false
  filter_adaptive_mean: true
  postprocess_only_left: true
  subsampling: false
# configuration for sparse features.
sparse_config:
  debugImage: true
  targetNumFeatures: 100
  maxStereoYDeviation: 5
  knn: 1
  distanceFactor: 2
  isometryFilterMaxSteps: 1000
  isometryFilterThreshold: 0.1
  adaptiveDetectorParam: false
  detectorConfig:
    SURFparam: 170
    goodParam: 0.10000000149011612
    mserParam: 3.0
    starParam: 9.0
    fastParam: 12.0
  descriptorType: :DESCRIPTOR_PSURF
  detectorType: :DETECTOR_MSER
  filterType: :FILTER_STEREO
# calibration parameters for stereo camera setup
stereoCameraCalibration:
  camLeft:
    fx: 822.227706935
    fy: 822.927185544
    cx: 500.570003209
    cy: 389.677579798
    d0: -0.329304723377
    d1: 0.111047291678
    d2: 0.00112087517133
    d3: -0.000214995608353
    width: 1024
    height: 768
    ex: 0
    ey: 0
  camRight:
    fx: 826.863502923
    fy: 825.62436397
    cx: 490.041877899
    cy: 382.244076897
    d0: -0.335039958312
    d1: 0.119533691278
    d2: 0.000731208184955
    d3: -0.00070900223821
    width: 1024
    height: 768
    ex: 0.0
    ey: 0.0
#Distance between left and right camera
  extrinsic:
    tx: -120.4224030000000
    ty: 0.3256255180000000
    tz: -0.07402001730000000
    rx: -0.001819615757731449
    ry: -0.008842211883599646
    rz: -0.003584645009846816
output_format_sync: :MODE_GRAYSCALE

--- name:hdpr_bb2_ga_slam_tenerife
# gaussian kernel for dense stereo pre-processing.
gaussian_kernel: 0
# if set to true, the input images are assumed to already be rectified.
image_rectified: false
# if set to true, the input images are assumed to be rotated by 180 degrees.
image_rotated: false
# down- or upscale input images by this factor.
image_scaling_factor: 1.0

# configuration values for libElas
libElas_conf:
  disp_min: 5
  disp_max: 350
  support_threshold: 0.8500000238418579
  support_texture: 10
  candidate_stepsize: 5
  incon_window_size: 5
  incon_threshold: 5
  incon_min_support: 5
  add_corners: false
  grid_size: 20
  beta: 0.019999999552965164
  gamma: 3.0
  sigma: 1.0
  sradius: 2.0
  match_texture: 1
  lr_threshold: 2
  speckle_sim_threshold: 1.0
  speckle_size: 200
  ipol_gap_width: 3
  filter_median: false
  filter_adaptive_mean: true
  postprocess_only_left: true
  subsampling: false
# configuration for sparse features.
sparse_config:
  debugImage: true
  targetNumFeatures: 100
  maxStereoYDeviation: 5
  knn: 1
  distanceFactor: 2
  isometryFilterMaxSteps: 1000
  isometryFilterThreshold: 0.1
  adaptiveDetectorParam: false
  detectorConfig:
    SURFparam: 170
    goodParam: 0.10000000149011612
    mserParam: 3.0
    starParam: 9.0
    fastParam: 12.0
  descriptorType: :DESCRIPTOR_PSURF
  detectorType: :DETECTOR_MSER
  filterType: :FILTER_STEREO
# calibration parameters for stereo camera setup
#stereoCameraCalibration:
#  camLeft:
#    fx: 837.253850
#    fy: 838.490409
#    cx: 500.836269
#    cy: 396.129781
#    d0: -0.350699 
#    d1: 0.143871 
#    d2: 0.000772 
#    d3: 0.000436
#    width: 1024
#    height: 768
#  camRight:
#    fx: 840.576003
#    fy: 839.660192
#    cx: 486.582638
#    cy: 390.268319
#    d0: -0.349734 
#    d1: 0.140961 
#    d2: 0.000373 
#    d3: 0.000030
#    width: 1024
#    height: 768
##Distance between left and right camera
#  extrinsic:
#    tx: -121.85240164807148
#    ty: 0.1948076202153522
#    tz: -0.39816877115110094
#    rx: -0.00012901913800443746
#    ry: -0.0038610733653918344
#    rz: -0.0033187483729531205
# Calibration results from Kalibr
stereoCameraCalibration:
  camLeft:
    fx: 833.029249273
    fy: 834.36200043
    cx: 503.38475908
    cy: 394.969563968
    d0: -0.351348570994
    d1: 0.149480797792
    d2: 0.000305233424184
    d3: -0.000750163647335
    width: 1024
    height: 768
  camRight:
    fx: 838.801936516
    fy: 838.480016878
    cx: 487.625364421
    cy: 387.634126099
    d0: -0.356833447233
    d1: 0.161196429937
    d2: 0.000303425633673
    d3: -0.000540901163595
    width: 1024
    height: 768
#Distance between left and right camera
  extrinsic:
    tx: -119.2447700000000
    ty: 0.1109700000000000
    tz: 1.691040000000000
    rx: -0.002033295208862309
    ry: -0.003170676988095988
    rz: -0.003374311026266406

--- name:egp_bb2
# gaussian kernel for dense stereo pre-processing.
gaussian_kernel: 0
# if set to true, the input images are assumed to already be rectified.
image_rectified: false
# if set to true, the input images are assumed to be rotated by 180 degrees.
image_rotated: false
# down- or upscale input images by this factor.
image_scaling_factor: 1.0
# configuration values for libElas
libElas_conf:
  disp_min: 0
  disp_max: 350
  support_threshold: 0.8500000238418579
  support_texture: 10
  candidate_stepsize: 5
  incon_window_size: 5
  incon_threshold: 5
  incon_min_support: 5
  add_corners: true
  grid_size: 20
  beta: 0.019999999552965164
  gamma: 3.0
  sigma: 1.0
  sradius: 2.0
  match_texture: 1
  lr_threshold: 2
  speckle_sim_threshold: 1.0
  speckle_size: 200
  ipol_gap_width: 3
  filter_median: false
  filter_adaptive_mean: true
  postprocess_only_left: true
  subsampling: false
# configuration for sparse features.
sparse_config:
  debugImage: true
  targetNumFeatures: 100
  maxStereoYDeviation: 5
  knn: 1
  distanceFactor: 2
  isometryFilterMaxSteps: 1000
  isometryFilterThreshold: 0.1
  adaptiveDetectorParam: false
  detectorConfig:
    SURFparam: 170
    goodParam: 0.10000000149011612
    mserParam: 3.0
    starParam: 9.0
    fastParam: 12.0
  descriptorType: :DESCRIPTOR_PSURF
  detectorType: :DETECTOR_MSER
  filterType: :FILTER_STEREO
# calibration parameters for stereo camera setup
stereoCameraCalibration:
  camLeft:
    fx: 524.766677768
    fy: 526.74578325
    cx: 527.913386294
    cy: 389.222780504
    d0: -0.278923853445
    d1: 0.0557613853364
    d2: 0.00146102870003
    d3: 5.68636874228e-05
    width: 1024
    height: 768
    ex: 0
    ey: 0
  camRight:
    fx: 522.653509665
    fy: 525.187263599
    cx: 512.970763864
    cy: 391.93214631
    d0: -0.27102163415
    d1: 0.0509259624219
    d2: 0.00169221086887
    d3: -0.0001808835454
    width: 1024
    height: 768
    ex: 0.0
    ey: 0.0
#Distance between left and right camera
  extrinsic:
    tx: -120.4774600000000
    ty: 0.4719400000000000
    tz: 1.502740000000000
    rx: -0.006216684300016592
    ry: 0.02853943082947520
    rz: 0.005659517902708327
#output_format_sync: :MODE_GRAYSCALE
output_format_sync: :MODE_RGB


--- name:hdpr_bb3_left_right
# gaussian kernel for dense stereo pre-processing.
gaussian_kernel: 0
# if set to true, the input images are assumed to already be rectified.
image_rectified: false
# if set to true, the input images are assumed to be rotated by 180 degrees.
image_rotated: false
# down- or upscale input images by this factor.
image_scaling_factor: 1.0
# configuration values for libElas
libElas_conf:
  disp_min: 5
  disp_max: 350
  support_threshold: 0.8500000238418579
  support_texture: 10
  candidate_stepsize: 5
  incon_window_size: 5
  incon_threshold: 5
  incon_min_support: 5
  add_corners: false
  grid_size: 20
  beta: 0.019999999552965164
  gamma: 3.0
  sigma: 1.0
  sradius: 2.0
  match_texture: 1
  lr_threshold: 2
  speckle_sim_threshold: 1.0
  speckle_size: 200
  ipol_gap_width: 3
  filter_median: false
  filter_adaptive_mean: true
  postprocess_only_left: true
  subsampling: false
# configuration for sparse features.
sparse_config:
  debugImage: true
  targetNumFeatures: 100
  maxStereoYDeviation: 5
  knn: 1
  distanceFactor: 2
  isometryFilterMaxSteps: 1000
  isometryFilterThreshold: 0.1
  adaptiveDetectorParam: false
  detectorConfig:
    SURFparam: 170
    goodParam: 0.10000000149011612
    mserParam: 3.0
    starParam: 9.0
    fastParam: 12.0
  descriptorType: :DESCRIPTOR_PSURF
  detectorType: :DETECTOR_MSER
  filterType: :FILTER_STEREO
# calibration parameters for stereo camera setup
stereoCameraCalibration:
  camLeft:
    fx: 1636.20761888
    fy: 1637.33777994
    cx: 651.850565473
    cy: 471.147308853
    d0: -0.594977746871
    d1: 0.325393349407
    d2: 0.00144401244969
    d3: 0.000959205363921
    width: 1280
    height: 960
  camRight:
    fx: 1639.72518101
    fy: 1640.90202338
    cx: 646.514647735
    cy: 475.276983991
    d0: -0.595106148265
    d1: 0.331023501494
    d2: 0.00238172923311
    d3: -0.000967072920991
    width: 1280
    height: 960
#Distance between left and right camera
  extrinsic:
    tx: -2.39663482e+02
    ty: -8.14723521e-02
    tz: -5.67111539e-01
    rx: 0.006304017079544317
    ry: -0.0012146750982623684
    rz: -0.0029615554641445854
#output_format_sync: :MODE_GRAYSCALE
output_format_sync: :MODE_RGB

--- name:marta_bb3_left_right
# gaussian kernel for dense stereo pre-processing.
gaussian_kernel: 0
# if set to true, the input images are assumed to already be rectified.
image_rectified: false
# if set to true, the input images are assumed to be rotated by 180 degrees.
image_rotated: false
# down- or upscale input images by this factor.
image_scaling_factor: 1.0
# configuration values for libElas
libElas_conf:
  disp_min: 5
  disp_max: 350
  support_threshold: 0.8500000238418579
  support_texture: 10
  candidate_stepsize: 5
  incon_window_size: 5
  incon_threshold: 5
  incon_min_support: 5
  add_corners: false
  grid_size: 20
  beta: 0.019999999552965164
  gamma: 3.0
  sigma: 1.0
  sradius: 2.0
  match_texture: 1
  lr_threshold: 2
  speckle_sim_threshold: 1.0
  speckle_size: 200
  ipol_gap_width: 3
  filter_median: false
  filter_adaptive_mean: true
  postprocess_only_left: true
  subsampling: false
# configuration for sparse features.
sparse_config:
  debugImage: true
  targetNumFeatures: 100
  maxStereoYDeviation: 5
  knn: 1
  distanceFactor: 2
  isometryFilterMaxSteps: 1000
  isometryFilterThreshold: 0.1
  adaptiveDetectorParam: false
  detectorConfig:
    SURFparam: 170
    goodParam: 0.10000000149011612
    mserParam: 3.0
    starParam: 9.0
    fastParam: 12.0
  descriptorType: :DESCRIPTOR_PSURF
  detectorType: :DETECTOR_MSER
  filterType: :FILTER_STEREO
# calibration parameters for stereo camera setup
stereoCameraCalibration:
  camLeft:
    fx: 1645.51714174
    fy: 1646.09752195
    cx: 631.156776829
    cy: 480.300988996
    d0: -0.444317086558
    d1: 0.264611770415
    d2: -0.00164976520823
    d3: 0.000231870965717
    width: 1280
    height: 960
    ex: 0
    ey: 0
  camRight:
    fx: 1627.78455487
    fy: 1627.16755792
    cx: 652.187178655
    cy: 469.893048887
    d0: -0.4428254944
    d1: 0.24504703595
    d2: -0.000283744955525
    d3: -0.00146112860417
    width: 1280
    height: 960
    ex: 0.0
    ey: 0.0
#Distance between left and right camera
  extrinsic:
    tx: -239.5201200000000
    ty: 0.3888600000000000
    tz: 1.467990000000000
    rx: 0.003034434388698680
    ry: 0.002180973564268589
    rz: -0.004953862715956596
output_format_sync: :MODE_GRAYSCALE

--- name:panCam
# gaussian kernel for dense stereo pre-processing.
gaussian_kernel: 0
# if set to true, the input images are assumed to already be rectified.
image_rectified: false
# if set to true, the input images are assumed to be rotated by 180 degrees.
image_rotated: false
# down- or upscale input images by this factor.
image_scaling_factor: 1.0
# configuration values for libElas
libElas_conf:
  disp_min: 5
  disp_max: 350
  support_threshold: 0.8500000238418579
  support_texture: 10
  candidate_stepsize: 5
  incon_window_size: 5
  incon_threshold: 5
  incon_min_support: 5
  add_corners: false
  grid_size: 20
  beta: 0.019999999552965164
  gamma: 3.0
  sigma: 1.0
  sradius: 2.0
  match_texture: 1
  lr_threshold: 2
  speckle_sim_threshold: 1.0
  speckle_size: 200
  ipol_gap_width: 3
  filter_median: false
  filter_adaptive_mean: true
  postprocess_only_left: true
  subsampling: false
# configuration for sparse features.
sparse_config:
  debugImage: true
  targetNumFeatures: 100
  maxStereoYDeviation: 5
  knn: 1
  distanceFactor: 2
  isometryFilterMaxSteps: 1000
  isometryFilterThreshold: 0.1
  adaptiveDetectorParam: false
  detectorConfig:
    SURFparam: 170
    goodParam: 0.10000000149011612
    mserParam: 3.0
    starParam: 9.0
    fastParam: 12.0
  descriptorType: :DESCRIPTOR_PSURF
  detectorType: :DETECTOR_MSER
  filterType: :FILTER_STEREO
# calibration parameters for stereo camera setup
stereoCameraCalibration:
  camLeft:
    fx: 1434.34057864
    fy: 1434.48156538
    cx: 656.482491027
    cy: 478.284247083
    d0: -0.260171121309
    d1: 0.209943290439
    d2: -0.000130643979542
    d3: 0.000255815643856
    width: 1280
    height: 960
    ex: 0
    ey: 0
  camRight:
    fx: 1436.38539084
    fy: 1435.84256671
    cx: 659.435415806
    cy: 485.682779254
    d0: -0.258044200466
    d1: 0.207252488943
    d2: -0.000466549247419
    d3: 0.000308251936016
    width: 1280
    height: 960
    ex: 0.0
    ey: 0.0
#Distance between left and right camera
  extrinsic:
    tx: -499.1893100000000
    ty: 1.461460000000000
    tz: -5.001850000000000
    rx: -0.002154805092804208
    ry: 0.0006652668141734516
    rz: -0.0002057358731394412
